#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:    
    psycopg2.connect(
        dbname="${NAME},
        user="${USER}",
        password="${PASSWORD}",
        host="${HOST}",
        port="${PORT}",
    )
except psycopg2.OperationError:
    sys.exit(1)
sys.exit(0)

END
}
until postgres_ready; do
    >&2 echo "Waiting for PostgreSQL to become avialable..."
done
>&2 echo "PostgreSQL is avialable"

exec "$@"

