#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py createadmin


python manage.py collectstatic --no-input

exec gunicorn core.wsgi:application --bind 0.0.0.0:8000