# Generated by Django 5.0.3 on 2024-07-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
