# Generated by Django 5.0.3 on 2024-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_bg_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='folowings',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='folowings',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='folowers', to='users.useraccount'),
        ),
    ]
