# Generated by Django 5.0.3 on 2024-07-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akromdev', '0006_picture_author_alter_audio_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='akromdev.audiocategory'),
            preserve_default=False,
        ),
    ]
