# Generated by Django 5.0.3 on 2024-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akromdev', '0009_picture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d'),
        ),
    ]
